export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADDED_MENU_ITEM_FAIL = "ADDED_MENU_ITEM_FAIL";
export const ADDED_MENU_ITEM = "ADDED_MENU_ITEM";
export const MENU_ITEMS_LOADED = "MENU_ITEMS_LOADED";
export const MENU_ITEMS_LOADING_FAIL = "MENU_ITEMS_LOADING_FAIL";

export const EVENT_ITEMS_LOADED = "MENU_ITEMS_LOADING_FAIL";
export const EVENT_ITEMS_LOADING_FAIL = "MENU_ITEMS_LOADING_FAIL";
export const ADDED_EVENT_ITEM = "ADDED_EVENT_ITEM";
export const ADDED_EVENT_ITEM_FAIL = "ADDED_EVENT_ITEM_FAIL";


