export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const ADDED_MENU_ITEM_FAIL = "ADDED_MENU_ITEM_FAIL";
export const ADDED_MENU_ITEM = "ADDED_MENU_ITEM";
export const MENU_ITEMS_LOADED = "MENU_ITEMS_LOADED";
export const MENU_ITEMS_LOADING_FAIL = "MENU_ITEMS_LOADING_FAIL";

export const EVENT_ITEMS_LOADED = "EVENT_ITEMS_LOADING_FAIL";
export const EVENT_ITEMS_LOADING_FAIL = "EVENT_ITEMS_LOADING_FAIL";
export const ADDED_EVENT_ITEM = "ADDED_EVENT_ITEM";
export const ADDED_EVENT_ITEM_FAIL = "ADDED_EVENT_ITEM_FAIL";

export const RESERVATION_LOADED = "RESERVATION_LOADING";
export const RESERVATION_LOADING_FAIL = "RESERVATION_LOADING_FAIL";
export const ADDED_RESERVATION = "ADDED_RESERVATION";
export const ADDED_RESERVATION_FAIL = "ADDED_RESERVATION_FAIL";


export const TEAM_LOADED = "TEAM_LOADED";
export const TEAM_LOADING_FAIL = "TEAM_LOADING_FAIL";
export const ADDED_TEAM_MEMBER = "ADDED_TEAM_MEMBER";
export const ADDED_TEAM_MEMBER_FAIL = "ADDED_TEAM_MEMBER_FAIL";

